<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="Micro Focus UFT One" productVer="2021" os="Windows 10" host="vm001"><DocLocation><![CDATA[C:\Users\sfjbs\Desktop\UFT\Framework\DataDrivenFramework\Driver\Driver]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus UFT One"  >
<DName><![CDATA[Driver]]></DName>
<Res><![CDATA[Res28]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[tr1]]></Obj>
<Details plainTxt="False" ><![CDATA[Transaction "tr1" started.]]></Details>
<Time><![CDATA[4/3/2022 - 11:51:51]]></Time>
<TimeTick>1648966911</TimeTick>
<NodeArgs eType="Transaction" icon="5" nRep="8" nType="Start Transaction" Source="Action1" SourceLine="3" >
<Disp><![CDATA[tr1]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[4/3/2022 - 11:52:04]]></Time>
<TimeTick>1648966924</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\UFT One\samples\Flights Application\FlightsGUI.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\UFT One\samples\Flights Application\FlightsGUI.exe",1]]></Details>
<Time><![CDATA[4/3/2022 - 11:52:04]]></Time>
<TimeTick>1648966924</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="12" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files (x86)\Micro Focus\UFT One\samples\Flights Application\FlightsGUI.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="11" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[4/3/2022 - 11:52:12]]></Time>
<TimeTick>1648966932</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[agentName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["john"]]></Details>
<Time><![CDATA[4/3/2022 - 11:52:12]]></Time>
<TimeTick>1648966932</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="15" >
<Disp><![CDATA[agentName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["hp"]]></Details>
<Time><![CDATA[4/3/2022 - 11:52:12]]></Time>
<TimeTick>1648966932</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="17" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/3/2022 - 11:52:13]]></Time>
<TimeTick>1648966933</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="19" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/3/2022 - 11:52:14]]></Time>
<TimeTick>1648966934</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="20" >
<Disp><![CDATA[Micro Focus MyFlight Sample.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="14" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj ><![CDATA[Login]]></Obj>
<Details ><![CDATA[Login Successful]]></Details>
<Time><![CDATA[4/3/2022 - 11:52:14]]></Time>
<TimeTick>1648966934</TimeTick>
<NodeArgs eType="User" icon="10" nRep="21" status="Passed" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[4/3/2022 - 11:52:15]]></Time>
<TimeTick>1648966935</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/3/2022 - 11:52:15]]></Time>
<TimeTick>1648966935</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="24" >
<Disp><![CDATA[Micro Focus MyFlight Sample.Close]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/3/2022 - 11:52:26]]></Time>
<TimeTick>1648966946</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="26" >
<Disp><![CDATA[Micro Focus MyFlight Sample.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="23" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj ><![CDATA[closeapp]]></Obj>
<Details ><![CDATA[closeapp Successful]]></Details>
<Time><![CDATA[4/3/2022 - 11:52:26]]></Time>
<TimeTick>1648966946</TimeTick>
<NodeArgs eType="User" icon="10" nRep="27" status="Passed" >
<Disp><![CDATA[closeapp]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[4/3/2022 - 11:55:43]]></Time>
<TimeTick>1648967143</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\UFT One\samples\Flights Application\FlightsGUI.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\UFT One\samples\Flights Application\FlightsGUI.exe",1]]></Details>
<Time><![CDATA[4/3/2022 - 11:55:43]]></Time>
<TimeTick>1648967143</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="31" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files (x86)\Micro Focus\UFT One\samples\Flights Application\FlightsGUI.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="30" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[4/3/2022 - 11:55:51]]></Time>
<TimeTick>1648967151</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[agentName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["john"]]></Details>
<Time><![CDATA[4/3/2022 - 11:55:51]]></Time>
<TimeTick>1648967151</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="34" >
<Disp><![CDATA[agentName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["hp"]]></Details>
<Time><![CDATA[4/3/2022 - 11:55:51]]></Time>
<TimeTick>1648967151</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="36" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/3/2022 - 11:55:52]]></Time>
<TimeTick>1648967152</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="38" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/3/2022 - 11:55:52]]></Time>
<TimeTick>1648967152</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="39" >
<Disp><![CDATA[Micro Focus MyFlight Sample.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="33" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj ><![CDATA[Login]]></Obj>
<Details ><![CDATA[Login Successful]]></Details>
<Time><![CDATA[4/3/2022 - 11:55:52]]></Time>
<TimeTick>1648967152</TimeTick>
<NodeArgs eType="User" icon="10" nRep="40" status="Passed" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[4/3/2022 - 11:55:55]]></Time>
<TimeTick>1648967155</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/3/2022 - 11:55:55]]></Time>
<TimeTick>1648967155</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="43" >
<Disp><![CDATA[Micro Focus MyFlight Sample.Close]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/3/2022 - 11:56:05]]></Time>
<TimeTick>1648967165</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="45" >
<Disp><![CDATA[Micro Focus MyFlight Sample.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="42" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj ><![CDATA[closeapp]]></Obj>
<Details ><![CDATA[closeapp Successful]]></Details>
<Time><![CDATA[4/3/2022 - 11:56:05]]></Time>
<TimeTick>1648967165</TimeTick>
<NodeArgs eType="User" icon="10" nRep="46" status="Passed" >
<Disp><![CDATA[closeapp]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[4/3/2022 - 11:56:07]]></Time>
<TimeTick>1648967167</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\UFT One\samples\Flights Application\FlightsGUI.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\UFT One\samples\Flights Application\FlightsGUI.exe",1]]></Details>
<Time><![CDATA[4/3/2022 - 11:56:07]]></Time>
<TimeTick>1648967167</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="50" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files (x86)\Micro Focus\UFT One\samples\Flights Application\FlightsGUI.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="49" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[4/3/2022 - 11:56:15]]></Time>
<TimeTick>1648967175</TimeTick>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[agentName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["john"]]></Details>
<Time><![CDATA[4/3/2022 - 11:56:15]]></Time>
<TimeTick>1648967175</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="53" >
<Disp><![CDATA[agentName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["hp"]]></Details>
<Time><![CDATA[4/3/2022 - 11:56:15]]></Time>
<TimeTick>1648967175</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="55" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/3/2022 - 11:56:15]]></Time>
<TimeTick>1648967175</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="57" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/3/2022 - 11:56:16]]></Time>
<TimeTick>1648967176</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="58" >
<Disp><![CDATA[Micro Focus MyFlight Sample.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="52" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj ><![CDATA[Login]]></Obj>
<Details ><![CDATA[Login Successful]]></Details>
<Time><![CDATA[4/3/2022 - 11:56:16]]></Time>
<TimeTick>1648967176</TimeTick>
<NodeArgs eType="User" icon="10" nRep="59" status="Passed" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[4/3/2022 - 11:56:58]]></Time>
<TimeTick>1648967218</TimeTick>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"Micro&nbsp;Focus&nbsp;MyFlight&nbsp;Sample"&nbsp;(of&nbsp;class&nbsp;WpfWindow).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[4/3/2022 - 11:56:58]]></Time>
<TimeTick>1648967218</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>wpftypename = window<br>regexpwndtitle = Micro Focus MyFlight Sample Application<br>devname = Micro Focus MyFlight Sample Application<br>]]></Details>
<Time><![CDATA[4/3/2022 - 11:56:58]]></Time>
<TimeTick>1648967218</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="64" status="Warning" nType="Description" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="7" nRep="63" status="Failed" nType="Run Error" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="62" status="Failed" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[4/3/2022 - 11:56:58]]></Time>
<TimeTick>1648967218</TimeTick>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;Micro Focus MyFlight Sample&quot; (of class WpfWindow).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Function file: C:\Users\sfjbs\Desktop\UFT\Framework\DataDrivenFramework\FunctionLIbrary\Library1.qfl<BR/>Line (19): &quot;	WpfWindow(&quot;Micro Focus MyFlight Sample&quot;).Close&quot;.]]></Details>
<Time><![CDATA[4/3/2022 - 11:56:58]]></Time>
<TimeTick>1648967218</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="66" status="Failed" Source="C:\Users\sfjbs\Desktop\UFT\Framework\DataDrivenFramework\FunctionLIbrary\Library1.qfl" SourceLine="18" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[4/3/2022 - 11:57:04]]></Time>
<TimeTick>1648967224</TimeTick>
<NodeArgs eType="General" icon="12" nRep="67" status="Information" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="65" status="Failed" Source="C:\Users\sfjbs\Desktop\UFT\Framework\DataDrivenFramework\FunctionLIbrary\Library1.qfl" SourceLine="-1" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="4/3/2022 - 11:51:50" eTime="4/3/2022 - 11:57:04" passed="8" failed="2" warnings="1" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Failed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[Driver Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="4/3/2022 - 11:51:44" eTime="4/3/2022 - 11:57:04" passed="8" failed="2" warnings="1" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test Driver Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>