<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="Micro Focus UFT One" productVer="2021" os="Windows 10" host="vm001"><DocLocation><![CDATA[C:\Users\sfjbs\Desktop\UFT\Framework\KeywordDrivenFramework\Driver\Driver]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus UFT One"  >
<DName><![CDATA[Driver]]></DName>
<Res><![CDATA[Res22]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[tr1]]></Obj>
<Details plainTxt="False" ><![CDATA[Transaction "tr1" started.]]></Details>
<Time><![CDATA[4/2/2022 - 23:40:49]]></Time>
<TimeTick>1648923049</TimeTick>
<NodeArgs eType="Transaction" icon="5" nRep="8" nType="Start Transaction" Source="Action1" SourceLine="3" >
<Disp><![CDATA[tr1]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[4/2/2022 - 23:40:58]]></Time>
<TimeTick>1648923058</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\UFT One\samples\Flights Application\FlightsGUI.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\UFT One\samples\Flights Application\FlightsGUI.exe",1]]></Details>
<Time><![CDATA[4/2/2022 - 23:40:58]]></Time>
<TimeTick>1648923058</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="12" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files (x86)\Micro Focus\UFT One\samples\Flights Application\FlightsGUI.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="11" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[4/2/2022 - 23:40:59]]></Time>
<TimeTick>1648923059</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[agentName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["john"]]></Details>
<Time><![CDATA[4/2/2022 - 23:40:59]]></Time>
<TimeTick>1648923059</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="18" >
<Disp><![CDATA[agentName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["hp"]]></Details>
<Time><![CDATA[4/2/2022 - 23:40:59]]></Time>
<TimeTick>1648923059</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="20" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/2/2022 - 23:41:00]]></Time>
<TimeTick>1648923060</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="22" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/2/2022 - 23:41:00]]></Time>
<TimeTick>1648923060</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="23" >
<Disp><![CDATA[Micro Focus MyFlight Sample.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="17" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj ><![CDATA[Login]]></Obj>
<Details ><![CDATA[Login Successful]]></Details>
<Time><![CDATA[4/2/2022 - 23:41:00]]></Time>
<TimeTick>1648923060</TimeTick>
<NodeArgs eType="User" icon="10" nRep="24" status="Passed" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[4/2/2022 - 23:41:02]]></Time>
<TimeTick>1648923062</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/2/2022 - 23:41:02]]></Time>
<TimeTick>1648923062</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="27" >
<Disp><![CDATA[Micro Focus MyFlight Sample.Close]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/2/2022 - 23:41:13]]></Time>
<TimeTick>1648923073</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="29" >
<Disp><![CDATA[Micro Focus MyFlight Sample.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="26" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj ><![CDATA[closeapp]]></Obj>
<Details ><![CDATA[closeapp Successful]]></Details>
<Time><![CDATA[4/2/2022 - 23:41:13]]></Time>
<TimeTick>1648923073</TimeTick>
<NodeArgs eType="User" icon="10" nRep="30" status="Passed" >
<Disp><![CDATA[closeapp]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[4/2/2022 - 23:41:19]]></Time>
<TimeTick>1648923079</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\UFT One\samples\Flights Application\FlightsGUI.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\UFT One\samples\Flights Application\FlightsGUI.exe",1]]></Details>
<Time><![CDATA[4/2/2022 - 23:41:19]]></Time>
<TimeTick>1648923079</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="34" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files (x86)\Micro Focus\UFT One\samples\Flights Application\FlightsGUI.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="33" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[4/2/2022 - 23:41:20]]></Time>
<TimeTick>1648923080</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[agentName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["john"]]></Details>
<Time><![CDATA[4/2/2022 - 23:41:20]]></Time>
<TimeTick>1648923080</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="40" >
<Disp><![CDATA[agentName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["hp"]]></Details>
<Time><![CDATA[4/2/2022 - 23:41:20]]></Time>
<TimeTick>1648923080</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="42" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/2/2022 - 23:41:21]]></Time>
<TimeTick>1648923081</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="44" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/2/2022 - 23:41:21]]></Time>
<TimeTick>1648923081</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="45" >
<Disp><![CDATA[Micro Focus MyFlight Sample.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="39" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj ><![CDATA[Login]]></Obj>
<Details ><![CDATA[Login Successful]]></Details>
<Time><![CDATA[4/2/2022 - 23:41:21]]></Time>
<TimeTick>1648923081</TimeTick>
<NodeArgs eType="User" icon="10" nRep="46" status="Passed" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[4/2/2022 - 23:41:27]]></Time>
<TimeTick>1648923087</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[WpfTabStrip.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["SEARCH ORDER"]]></Details>
<Time><![CDATA[4/2/2022 - 23:41:27]]></Time>
<TimeTick>1648923087</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="49" >
<Disp><![CDATA[WpfTabStrip.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[byNumberRadio.Set]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/2/2022 - 23:41:27]]></Time>
<TimeTick>1648923087</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="51" >
<Disp><![CDATA[byNumberRadio.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[byNumberWatermark.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["3"]]></Details>
<Time><![CDATA[4/2/2022 - 23:41:27]]></Time>
<TimeTick>1648923087</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="53" >
<Disp><![CDATA[byNumberWatermark.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/2/2022 - 23:41:27]]></Time>
<TimeTick>1648923087</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="55" >
<Disp><![CDATA[SEARCH.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/2/2022 - 23:41:27]]></Time>
<TimeTick>1648923087</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="56" >
<Disp><![CDATA[Micro Focus MyFlight Sample.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="48" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj ><![CDATA[openOrder]]></Obj>
<Details ><![CDATA[openOrder Successful]]></Details>
<Time><![CDATA[4/2/2022 - 23:41:27]]></Time>
<TimeTick>1648923087</TimeTick>
<NodeArgs eType="User" icon="10" nRep="57" status="Passed" >
<Disp><![CDATA[openOrder]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[4/2/2022 - 23:41:32]]></Time>
<TimeTick>1648923092</TimeTick>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/2/2022 - 23:41:32]]></Time>
<TimeTick>1648923092</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="60" >
<Disp><![CDATA[Micro Focus MyFlight Sample.Close]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/2/2022 - 23:41:43]]></Time>
<TimeTick>1648923103</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="62" >
<Disp><![CDATA[Micro Focus MyFlight Sample.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="59" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj ><![CDATA[closeapp]]></Obj>
<Details ><![CDATA[closeapp Successful]]></Details>
<Time><![CDATA[4/2/2022 - 23:41:43]]></Time>
<TimeTick>1648923103</TimeTick>
<NodeArgs eType="User" icon="10" nRep="63" status="Passed" >
<Disp><![CDATA[closeapp]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[4/2/2022 - 23:42:29]]></Time>
<TimeTick>1648923149</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\UFT One\samples\Flights Application\FlightsGUI.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\UFT One\samples\Flights Application\FlightsGUI.exe",1]]></Details>
<Time><![CDATA[4/2/2022 - 23:42:29]]></Time>
<TimeTick>1648923149</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="67" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files (x86)\Micro Focus\UFT One\samples\Flights Application\FlightsGUI.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="66" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[4/2/2022 - 23:42:30]]></Time>
<TimeTick>1648923150</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[agentName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["john"]]></Details>
<Time><![CDATA[4/2/2022 - 23:42:30]]></Time>
<TimeTick>1648923150</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="73" >
<Disp><![CDATA[agentName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["hp"]]></Details>
<Time><![CDATA[4/2/2022 - 23:42:30]]></Time>
<TimeTick>1648923150</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="75" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/2/2022 - 23:42:30]]></Time>
<TimeTick>1648923150</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="77" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/2/2022 - 23:42:31]]></Time>
<TimeTick>1648923151</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="78" >
<Disp><![CDATA[Micro Focus MyFlight Sample.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="72" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj ><![CDATA[Login]]></Obj>
<Details ><![CDATA[Login Successful]]></Details>
<Time><![CDATA[4/2/2022 - 23:42:31]]></Time>
<TimeTick>1648923151</TimeTick>
<NodeArgs eType="User" icon="10" nRep="79" status="Passed" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[4/2/2022 - 23:42:33]]></Time>
<TimeTick>1648923153</TimeTick>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[WpfTabStrip.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["SEARCH ORDER"]]></Details>
<Time><![CDATA[4/2/2022 - 23:42:33]]></Time>
<TimeTick>1648923153</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="82" >
<Disp><![CDATA[WpfTabStrip.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[byNumberRadio.Set]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/2/2022 - 23:42:34]]></Time>
<TimeTick>1648923154</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="84" >
<Disp><![CDATA[byNumberRadio.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[byNumberWatermark.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["3"]]></Details>
<Time><![CDATA[4/2/2022 - 23:42:34]]></Time>
<TimeTick>1648923154</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="86" >
<Disp><![CDATA[byNumberWatermark.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/2/2022 - 23:42:34]]></Time>
<TimeTick>1648923154</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="88" >
<Disp><![CDATA[SEARCH.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/2/2022 - 23:42:34]]></Time>
<TimeTick>1648923154</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="89" >
<Disp><![CDATA[Micro Focus MyFlight Sample.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="81" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj ><![CDATA[openOrder]]></Obj>
<Details ><![CDATA[openOrder Successful]]></Details>
<Time><![CDATA[4/2/2022 - 23:42:34]]></Time>
<TimeTick>1648923154</TimeTick>
<NodeArgs eType="User" icon="10" nRep="90" status="Passed" >
<Disp><![CDATA[openOrder]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[4/2/2022 - 23:42:39]]></Time>
<TimeTick>1648923159</TimeTick>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[numOfTicketsCombo.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["1"]]></Details>
<Time><![CDATA[4/2/2022 - 23:42:39]]></Time>
<TimeTick>1648923159</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="93" >
<Disp><![CDATA[numOfTicketsCombo.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[updateBtn.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/2/2022 - 23:42:40]]></Time>
<TimeTick>1648923160</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="95" >
<Disp><![CDATA[updateBtn.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/2/2022 - 23:42:40]]></Time>
<TimeTick>1648923160</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="96" >
<Disp><![CDATA[Micro Focus MyFlight Sample.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="92" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj ><![CDATA[updateOrder]]></Obj>
<Details ><![CDATA[updateOrder Successful]]></Details>
<Time><![CDATA[4/2/2022 - 23:42:40]]></Time>
<TimeTick>1648923160</TimeTick>
<NodeArgs eType="User" icon="10" nRep="97" status="Passed" >
<Disp><![CDATA[updateOrder]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[4/2/2022 - 23:42:43]]></Time>
<TimeTick>1648923163</TimeTick>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/2/2022 - 23:42:43]]></Time>
<TimeTick>1648923163</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="100" >
<Disp><![CDATA[Micro Focus MyFlight Sample.Close]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/2/2022 - 23:42:53]]></Time>
<TimeTick>1648923173</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="102" >
<Disp><![CDATA[Micro Focus MyFlight Sample.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="99" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj ><![CDATA[closeapp]]></Obj>
<Details ><![CDATA[closeapp Successful]]></Details>
<Time><![CDATA[4/2/2022 - 23:42:53]]></Time>
<TimeTick>1648923173</TimeTick>
<NodeArgs eType="User" icon="10" nRep="103" status="Passed" >
<Disp><![CDATA[closeapp]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[tr1]]></Obj>
<Details plainTxt="False" ><![CDATA[Transaction "tr1" ended with "Pass" status (Total Duration: 124.4969 sec).]]></Details>
<Time><![CDATA[4/2/2022 - 23:42:54]]></Time>
<TimeTick>1648923174</TimeTick>
<NodeArgs eType="Transaction" icon="14" nRep="104" nType="End Transaction" Source="Action1" SourceLine="63" >
<Disp><![CDATA[tr1]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="4/2/2022 - 23:40:49" eTime="4/2/2022 - 23:42:54" passed="12" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T62">
<AName><![CDATA[Action2]]></AName>
<Summary sTime="4/2/2022 - 23:42:54" eTime="4/2/2022 - 23:42:54" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="106" >
<Disp><![CDATA[Action2 Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T63">
<AName><![CDATA[Action3]]></AName>
<Summary sTime="4/2/2022 - 23:42:54" eTime="4/2/2022 - 23:42:54" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="108" >
<Disp><![CDATA[Action3 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Passed" >
<Disp><![CDATA[Driver Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="4/2/2022 - 23:40:45" eTime="4/2/2022 - 23:42:54" passed="12" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Passed" >
<Disp><![CDATA[Test Driver Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>