<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="Micro Focus UFT One" productVer="2021" os="Windows 10" host="vm001"><DocLocation><![CDATA[C:\Users\sfjbs\Desktop\UFT\Framework\KeywordDrivenFramework\Driver\Driver]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus UFT One"  >
<DName><![CDATA[Driver]]></DName>
<Res><![CDATA[Res26]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[tr1]]></Obj>
<Details plainTxt="False" ><![CDATA[Transaction "tr1" started.]]></Details>
<Time><![CDATA[4/3/2022 - 0:24:24]]></Time>
<TimeTick>1648925664</TimeTick>
<NodeArgs eType="Transaction" icon="5" nRep="8" nType="Start Transaction" Source="Action1" SourceLine="3" >
<Disp><![CDATA[tr1]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[4/3/2022 - 0:24:39]]></Time>
<TimeTick>1648925679</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\UFT One\samples\Flights Application\FlightsGUI.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\UFT One\samples\Flights Application\FlightsGUI.exe",1]]></Details>
<Time><![CDATA[4/3/2022 - 0:24:39]]></Time>
<TimeTick>1648925679</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="12" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files (x86)\Micro Focus\UFT One\samples\Flights Application\FlightsGUI.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="11" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[4/3/2022 - 0:24:40]]></Time>
<TimeTick>1648925680</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[agentName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["john"]]></Details>
<Time><![CDATA[4/3/2022 - 0:24:41]]></Time>
<TimeTick>1648925681</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="17" >
<Disp><![CDATA[agentName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["hp"]]></Details>
<Time><![CDATA[4/3/2022 - 0:24:41]]></Time>
<TimeTick>1648925681</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="19" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/3/2022 - 0:24:41]]></Time>
<TimeTick>1648925681</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="21" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/3/2022 - 0:24:42]]></Time>
<TimeTick>1648925682</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="22" >
<Disp><![CDATA[Micro Focus MyFlight Sample.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="16" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj ><![CDATA[Login]]></Obj>
<Details ><![CDATA[Login Successful]]></Details>
<Time><![CDATA[4/3/2022 - 0:24:42]]></Time>
<TimeTick>1648925682</TimeTick>
<NodeArgs eType="User" icon="10" nRep="23" status="Passed" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[4/3/2022 - 0:24:44]]></Time>
<TimeTick>1648925684</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/3/2022 - 0:24:44]]></Time>
<TimeTick>1648925684</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="26" >
<Disp><![CDATA[Micro Focus MyFlight Sample.Close]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/3/2022 - 0:24:54]]></Time>
<TimeTick>1648925694</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="28" >
<Disp><![CDATA[Micro Focus MyFlight Sample.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="25" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj ><![CDATA[closeapp]]></Obj>
<Details ><![CDATA[closeapp Successful]]></Details>
<Time><![CDATA[4/3/2022 - 0:24:54]]></Time>
<TimeTick>1648925694</TimeTick>
<NodeArgs eType="User" icon="10" nRep="29" status="Passed" >
<Disp><![CDATA[closeapp]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[4/3/2022 - 0:25:00]]></Time>
<TimeTick>1648925700</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\UFT One\samples\Flights Application\FlightsGUI.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\UFT One\samples\Flights Application\FlightsGUI.exe",1]]></Details>
<Time><![CDATA[4/3/2022 - 0:25:00]]></Time>
<TimeTick>1648925700</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="33" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files (x86)\Micro Focus\UFT One\samples\Flights Application\FlightsGUI.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="32" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[4/3/2022 - 0:25:11]]></Time>
<TimeTick>1648925711</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[agentName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["john"]]></Details>
<Time><![CDATA[4/3/2022 - 0:25:11]]></Time>
<TimeTick>1648925711</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="38" >
<Disp><![CDATA[agentName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["hp"]]></Details>
<Time><![CDATA[4/3/2022 - 0:25:12]]></Time>
<TimeTick>1648925712</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="40" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[OK]]></Obj>
<Details plainTxt="False" ><![CDATA[Object&nbsp;is&nbsp;disabled]]></Details>
<Time><![CDATA[4/3/2022 - 0:25:12]]></Time>
<TimeTick>1648925712</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[OK]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Text = OK<br>devname = okButton<br>]]></Details>
<Time><![CDATA[4/3/2022 - 0:25:12]]></Time>
<TimeTick>1648925712</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="42" status="Warning" nType="Description" >
<Disp><![CDATA[OK]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="9" nRep="41" status="Failed" nType="Run Error" >
<Disp><![CDATA[OK]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="37" status="Failed" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[4/3/2022 - 0:25:12]]></Time>
<TimeTick>1648925712</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Object is disabled<BR/>Function file: C:\Users\sfjbs\Desktop\UFT\Framework\KeywordDrivenFramework\FunctionLIbrary\Library1.qfl<BR/>Line (6): &quot;WpfWindow(&quot;Micro Focus MyFlight Sample&quot;).WpfButton(&quot;OK&quot;).Click&quot;.]]></Details>
<Time><![CDATA[4/3/2022 - 0:25:12]]></Time>
<TimeTick>1648925712</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="44" status="Failed" Source="C:\Users\sfjbs\Desktop\UFT\Framework\KeywordDrivenFramework\FunctionLIbrary\Library1.qfl" SourceLine="5" >
<Disp><![CDATA[Run Error]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf2.xml]]></Path>
<ASHilite><![CDATA[8390750]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/3/2022 - 0:25:13]]></Time>
<TimeTick>1648925713</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="45" Source="C:\Users\sfjbs\Desktop\UFT\Framework\KeywordDrivenFramework\FunctionLIbrary\Library1.qfl" SourceLine="-1" >
<Disp><![CDATA[Micro Focus MyFlight Sample.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="43" status="Failed" Source="C:\Users\sfjbs\Desktop\UFT\Framework\KeywordDrivenFramework\FunctionLIbrary\Library1.qfl" SourceLine="-1" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf1.xml]]></Path>
<ASHilite><![CDATA[8390750]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj ><![CDATA[Login]]></Obj>
<Details ><![CDATA[Login Successful]]></Details>
<Time><![CDATA[4/3/2022 - 0:25:13]]></Time>
<TimeTick>1648925713</TimeTick>
<NodeArgs eType="User" icon="10" nRep="46" status="Passed" Source="C:\Users\sfjbs\Desktop\UFT\Framework\KeywordDrivenFramework\FunctionLIbrary\Library1.qfl" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[4/3/2022 - 0:25:37]]></Time>
<TimeTick>1648925737</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[WpfTabStrip]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"WpfTabStrip"&nbsp;(of&nbsp;class&nbsp;WpfTabStrip).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[4/3/2022 - 0:25:37]]></Time>
<TimeTick>1648925737</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[WpfTabStrip]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>wpftypename = tab<br>devnamepath = ;;<br>devname = <br>]]></Details>
<Time><![CDATA[4/3/2022 - 0:25:37]]></Time>
<TimeTick>1648925737</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="51" status="Warning" nType="Description" >
<Disp><![CDATA[WpfTabStrip]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="12" nRep="50" status="Failed" nType="Run Error" >
<Disp><![CDATA[WpfTabStrip]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="49" status="Failed" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[4/3/2022 - 0:25:37]]></Time>
<TimeTick>1648925737</TimeTick>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;WpfTabStrip&quot; (of class WpfTabStrip).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Function file: C:\Users\sfjbs\Desktop\UFT\Framework\KeywordDrivenFramework\FunctionLIbrary\Library1.qfl<BR/>Line (28): &quot;WpfWindow(&quot;Micro Focus MyFlight Sample&quot;).WpfTabStrip(&quot;WpfTabStrip&quot;).Select &quot;SEARCH ORDER&quot;&quot;.]]></Details>
<Time><![CDATA[4/3/2022 - 0:25:37]]></Time>
<TimeTick>1648925737</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="53" status="Failed" Source="C:\Users\sfjbs\Desktop\UFT\Framework\KeywordDrivenFramework\FunctionLIbrary\Library1.qfl" SourceLine="27" >
<Disp><![CDATA[Run Error]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf4.xml]]></Path>
<ASHilite><![CDATA[8390750]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[byNumberRadio.Set]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/3/2022 - 0:25:54]]></Time>
<TimeTick>1648925754</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="55" Source="C:\Users\sfjbs\Desktop\UFT\Framework\KeywordDrivenFramework\FunctionLIbrary\Library1.qfl" SourceLine="-1" >
<Disp><![CDATA[byNumberRadio.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[byNumberWatermark.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["3"]]></Details>
<Time><![CDATA[4/3/2022 - 0:25:54]]></Time>
<TimeTick>1648925754</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="57" Source="C:\Users\sfjbs\Desktop\UFT\Framework\KeywordDrivenFramework\FunctionLIbrary\Library1.qfl" SourceLine="-1" >
<Disp><![CDATA[byNumberWatermark.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/3/2022 - 0:25:54]]></Time>
<TimeTick>1648925754</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="59" Source="C:\Users\sfjbs\Desktop\UFT\Framework\KeywordDrivenFramework\FunctionLIbrary\Library1.qfl" SourceLine="-1" >
<Disp><![CDATA[SEARCH.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/3/2022 - 0:25:54]]></Time>
<TimeTick>1648925754</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="60" Source="C:\Users\sfjbs\Desktop\UFT\Framework\KeywordDrivenFramework\FunctionLIbrary\Library1.qfl" SourceLine="-1" >
<Disp><![CDATA[Micro Focus MyFlight Sample.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="52" status="Failed" Source="C:\Users\sfjbs\Desktop\UFT\Framework\KeywordDrivenFramework\FunctionLIbrary\Library1.qfl" SourceLine="-1" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf3.xml]]></Path>
<ASHilite><![CDATA[8390750]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj ><![CDATA[openOrder]]></Obj>
<Details ><![CDATA[openOrder Successful]]></Details>
<Time><![CDATA[4/3/2022 - 0:25:54]]></Time>
<TimeTick>1648925754</TimeTick>
<NodeArgs eType="User" icon="10" nRep="61" status="Passed" Source="C:\Users\sfjbs\Desktop\UFT\Framework\KeywordDrivenFramework\FunctionLIbrary\Library1.qfl" SourceLine="-1" >
<Disp><![CDATA[openOrder]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[4/3/2022 - 0:25:58]]></Time>
<TimeTick>1648925758</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/3/2022 - 0:25:58]]></Time>
<TimeTick>1648925758</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="64" >
<Disp><![CDATA[Micro Focus MyFlight Sample.Close]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/3/2022 - 0:26:08]]></Time>
<TimeTick>1648925768</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="66" >
<Disp><![CDATA[Micro Focus MyFlight Sample.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="63" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj ><![CDATA[closeapp]]></Obj>
<Details ><![CDATA[closeapp Successful]]></Details>
<Time><![CDATA[4/3/2022 - 0:26:08]]></Time>
<TimeTick>1648925768</TimeTick>
<NodeArgs eType="User" icon="10" nRep="67" status="Passed" >
<Disp><![CDATA[closeapp]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[4/3/2022 - 0:26:16]]></Time>
<TimeTick>1648925776</TimeTick>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\UFT One\samples\Flights Application\FlightsGUI.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\UFT One\samples\Flights Application\FlightsGUI.exe",1]]></Details>
<Time><![CDATA[4/3/2022 - 0:26:16]]></Time>
<TimeTick>1648925776</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="71" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files (x86)\Micro Focus\UFT One\samples\Flights Application\FlightsGUI.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="70" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[4/3/2022 - 0:26:27]]></Time>
<TimeTick>1648925787</TimeTick>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[agentName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["john"]]></Details>
<Time><![CDATA[4/3/2022 - 0:26:27]]></Time>
<TimeTick>1648925787</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="77" >
<Disp><![CDATA[agentName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["hp"]]></Details>
<Time><![CDATA[4/3/2022 - 0:26:27]]></Time>
<TimeTick>1648925787</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="79" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[OK]]></Obj>
<Details plainTxt="False" ><![CDATA[Object&nbsp;is&nbsp;disabled]]></Details>
<Time><![CDATA[4/3/2022 - 0:26:27]]></Time>
<TimeTick>1648925787</TimeTick>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[OK]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Text = OK<br>devname = okButton<br>]]></Details>
<Time><![CDATA[4/3/2022 - 0:26:27]]></Time>
<TimeTick>1648925787</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="81" status="Warning" nType="Description" >
<Disp><![CDATA[OK]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="9" nRep="80" status="Failed" nType="Run Error" >
<Disp><![CDATA[OK]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="76" status="Failed" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[4/3/2022 - 0:26:27]]></Time>
<TimeTick>1648925787</TimeTick>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Object is disabled<BR/>Function file: C:\Users\sfjbs\Desktop\UFT\Framework\KeywordDrivenFramework\FunctionLIbrary\Library1.qfl<BR/>Line (6): &quot;WpfWindow(&quot;Micro Focus MyFlight Sample&quot;).WpfButton(&quot;OK&quot;).Click&quot;.]]></Details>
<Time><![CDATA[4/3/2022 - 0:26:28]]></Time>
<TimeTick>1648925788</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="83" status="Failed" Source="C:\Users\sfjbs\Desktop\UFT\Framework\KeywordDrivenFramework\FunctionLIbrary\Library1.qfl" SourceLine="5" >
<Disp><![CDATA[Run Error]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf6.xml]]></Path>
<ASHilite><![CDATA[6817684]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/3/2022 - 0:26:28]]></Time>
<TimeTick>1648925788</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="84" Source="C:\Users\sfjbs\Desktop\UFT\Framework\KeywordDrivenFramework\FunctionLIbrary\Library1.qfl" SourceLine="-1" >
<Disp><![CDATA[Micro Focus MyFlight Sample.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="82" status="Failed" Source="C:\Users\sfjbs\Desktop\UFT\Framework\KeywordDrivenFramework\FunctionLIbrary\Library1.qfl" SourceLine="-1" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf5.xml]]></Path>
<ASHilite><![CDATA[6817684]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj ><![CDATA[Login]]></Obj>
<Details ><![CDATA[Login Successful]]></Details>
<Time><![CDATA[4/3/2022 - 0:26:28]]></Time>
<TimeTick>1648925788</TimeTick>
<NodeArgs eType="User" icon="10" nRep="85" status="Passed" Source="C:\Users\sfjbs\Desktop\UFT\Framework\KeywordDrivenFramework\FunctionLIbrary\Library1.qfl" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[4/3/2022 - 0:26:31]]></Time>
<TimeTick>1648925791</TimeTick>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[WpfTabStrip]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;find&nbsp;the&nbsp;"WpfTabStrip"&nbsp;object's&nbsp;parent&nbsp;"Micro&nbsp;Focus&nbsp;MyFlight&nbsp;Sample"&nbsp;(class&nbsp;WpfWindow).<br/>Verify&nbsp;that&nbsp;parent&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[4/3/2022 - 0:26:31]]></Time>
<TimeTick>1648925791</TimeTick>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>wpftypename = window<br>regexpwndtitle = Micro Focus MyFlight Sample Application<br>devname = Micro Focus MyFlight Sample Application<br>]]></Details>
<Time><![CDATA[4/3/2022 - 0:26:31]]></Time>
<TimeTick>1648925791</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="88" status="Warning" nType="Parent description" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="12" nRep="87" status="Failed" nType="Run Error" >
<Disp><![CDATA[WpfTabStrip]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[WpfTabStrip.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["SEARCH ORDER"]]></Details>
<Time><![CDATA[4/3/2022 - 0:26:42]]></Time>
<TimeTick>1648925802</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="91" >
<Disp><![CDATA[WpfTabStrip.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[byNumberRadio.Set]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/3/2022 - 0:26:42]]></Time>
<TimeTick>1648925802</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="93" >
<Disp><![CDATA[byNumberRadio.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[byNumberWatermark.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["3"]]></Details>
<Time><![CDATA[4/3/2022 - 0:26:42]]></Time>
<TimeTick>1648925802</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="95" >
<Disp><![CDATA[byNumberWatermark.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/3/2022 - 0:26:42]]></Time>
<TimeTick>1648925802</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="97" >
<Disp><![CDATA[SEARCH.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/3/2022 - 0:26:42]]></Time>
<TimeTick>1648925802</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="98" >
<Disp><![CDATA[Micro Focus MyFlight Sample.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="86" status="Failed" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj ><![CDATA[openOrder]]></Obj>
<Details ><![CDATA[openOrder Successful]]></Details>
<Time><![CDATA[4/3/2022 - 0:26:42]]></Time>
<TimeTick>1648925802</TimeTick>
<NodeArgs eType="User" icon="10" nRep="99" status="Passed" >
<Disp><![CDATA[openOrder]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[4/3/2022 - 0:26:47]]></Time>
<TimeTick>1648925807</TimeTick>
<Step rID="T64">